"""
Compares the filename and MD5 from the AIP bag manifests to the accession manifests for a processed collection
to find any files in the AIP that were altered during processing.

The filename is included in the match to remove the risk of an MD5 collision between two files,
but the file path is not used since folders may be moved or renamed.
This will identify any renamed files as a fixity change, but these are rare.

Parameters:
    collection_folder: path to the collection folder, which may have one or more accessions
    aips_directory: path to the folder with the bagged, unzipped version of the AIPs

Returns:
    aip_fixity_changes.csv: report with the MD5 and filepath of any AIP file that didn't match the accession

"""
import os
import pandas as pd
import sys


def accession_manifests(coll_folder):
    """Find every accession bag manifest in the collection folder and combine to one df"""

    # Start df for combined information, with columns already named.
    df_combined = pd.DataFrame(columns=['MD5', 'Path'])

    # Find each accession bag manifest based on the folder naming convention and combine into one df.
    # If a bag manifest is not in the expected location, print an error since it is probably a naming issue to fix.
    # The bag manifest splits md5 and path by 2 spaces, but paths can have 2 spaces elsewhere as well,
    # so the start of the path (data/) is also included in the delimiter.
    # The bag manifest has no header, so column names are assigned.
    for folder_name in os.listdir(coll_folder):
        if folder_name.lower().endswith('er') or folder_name.endswith('no-acc-num'):
            manifest_path = os.path.join(coll_folder, folder_name, f'{folder_name}_bag', 'manifest-md5.txt')
            try:
                df = pd.read_csv(manifest_path, delimiter='  data/', engine='python', header=None, names=['MD5', 'Path'])
                df_combined = pd.concat([df_combined, df], ignore_index=True)
            except FileNotFoundError:
                print(f'{manifest_path} not found')

    # Add a column with just the filename.
    df_combined['Filename'] = df_combined['Path'].str.split('/').str[-1]

    return df_combined


def aip_manifests(aips_dir):
    """Find every aip bag manifest in the collection folder and combine to one df"""

    # Start df for combined information, with columns already named.
    df_combined = pd.DataFrame(columns=['MD5', 'Path'])

    # Find each aip bag manifest and combine into one df.
    # Any folder inside aips_dir should be an AIP bag.
    # If a bag manifest is not in the expected location, print an error (unlikely).
    # See accession_manifests() for more details on the bag manifest.
    for folder_name in os.listdir(aips_dir):
        if os.path.isdir(os.path.join(aips_dir, folder_name)):
            manifest_path = os.path.join(aips_dir, folder_name, 'manifest-md5.txt')
            try:
                df = pd.read_csv(manifest_path, delimiter='  data/', engine='python', header=None, names=['MD5', 'Path'])
                df_combined = pd.concat([df_combined, df], ignore_index=True)
            except FileNotFoundError:
                print(f'{manifest_path} not found')

    # Only retain rows with a Path starting with objects.
    # The other rows are for metadata, which are generated by the AIP script and not in the accession(s).
    df_combined = df_combined[df_combined['Path'].str.startswith('objects')]

    # Add a column with just the filename.
    df_combined['Filename'] = df_combined['Path'].str.split('/').str[-1]

    return df_combined


def comparison_report(df_acc, df_aip, aips_dir):
    """Find any MD5 + Filename in an AIP that are not in an accession and save to a report"""

    # Compare the two dataframes and find MD5 + Filename combinations only in df_aip.
    df = df_aip.merge(df_acc, how='outer', on=['MD5', 'Filename'], indicator=True)
    df_aip_only = df[df['_merge'] == 'left_only']

    # Rename AIP path column and remove unnecessary columns for a simpler report.
    df_aip_only.rename(columns={'Path_x': 'Path'}, inplace=True)
    df_aip_only.drop(columns=['Path_y', '_merge'], inplace=True)

    # If any were found, save to a report in the parent directory of aips_dir (typically PreservationCopy).
    # If not, prints a message rather than saving an empty report.
    if len(df_aip_only) > 0:
        df_aip_only.to_csv(os.path.join(os.path.dirname(aips_dir), 'aip_fixity_changes.csv'), index=False)
    else:
        print("AIP fixity is unchanged")


if __name__ == '__main__':

    # Assign arguments to variables.
    collection_folder = sys.argv[1]
    aips_directory = sys.argv[2]

    # Find the accession bag manifests in the collection_folder and combine to one dataframe.
    df_accession = accession_manifests(collection_folder)

    # Find the AIP bag manifests in the aips_directory and combine into one dataframe.
    df_aips = aip_manifests(aips_directory)

    # Make a report with any file in an AIP with changed fixity, or print if all match.
    comparison_report(df_accession, df_aips, aips_directory)